### ISSUE TITLE
beta release checklist

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#193]
- [x] create a HISTORY.txt file to track changes after the beta release
- [x] edit repo branch permissions to allow push of a `do-release/**` branch directly to natcap's fork.
- [x] clear all other beta milestone issues
- [x] dev team installs and tests production builds on Windows & Mac
- [x] create new issues if needed, repeat previous steps.

======================================

- [x] All issues are resolved and dev team testing is done
- [x] create a `do-release/0.1.0-beta` branch
- [x] edit `HISTORY.rst` to add the release date, commit.
- [x] edit `package.json` `version` property with `0.1.0-beta` (I don't think any part of our process actually uses this string right now).
- [x] create a `0.1.0-beta` tag and push the tag & branch to `natcap/invest-workbench`. 
- [x] Download & install the builds from that push. They should be on our releases bucket.
- [x] The artifact should have a name like `invest_3.9.2.post470+g11795c5c_workbench_0.1.0-beta_win32_x64.exe`
- [x] The app should install to a folder (Windows) or `.app` (Mac) with a name like `InVEST 3.9.2.post470+g11795c5c Workbench 0.1.0-beta`
- [x] Create a github release object named `0.1.0-beta` choosing the `0.1.0-beta` tag. Add the `dmg` and `exe` as assets & publish.
- [x] Post download links to the forum & slack.
- [ ] merge `do-release/0.1.0-beta` into `main`
